name: CI
on:
  pull_request:
    branches:
      - "*"
jobs:
  validate-data:
    runs-on: ubuntu@22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Run validate data
        run: npm run test
